version: "3.5"

### Networks ###
networks:
  pub-network: {}
  pri-network:
    name: reverse-proxy

### Secrets ###
secrets:
  namesilo_api_key:
    file: ./secrets/namesilo_api_key.secret

### Volumes ###
volumes:
  letsencrypt: {}

### Services ###
services:
  # Reverse proxy
  proxy:
    image: traefik:v2.0
    command:
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.network=reverse-proxy"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--entrypoints.metrics.address=:8082"
      - "--certificatesresolvers.mydnschallenge.acme.email=admin@example.com"
      - "--certificatesresolvers.mydnschallenge.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.mydnschallenge.acme.dnschallenge=true"
      - "--certificatesresolvers.mydnschallenge.acme.dnschallenge.provider=namesilo"
      # - "--certificatesresolvers.mydnschallenge.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      # - "--log.level=DEBUG"
      - "--metrics.prometheus=true"
      - "--metrics.prometheus.entryPoint=metrics"
    environment:
      NAMESILO_API_KEY_FILE: /run/secrets/namesilo_api_key
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`proxy.example.com`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.api.entrypoints=http"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=secured"
      - "traefik.http.routers.api.tls.certresolver=mydnschallenge"
      - "traefik.http.middlewares.secured.chain.middlewares=https-only,known-ips,auth-users"
      - "traefik.http.middlewares.https-only.redirectscheme.scheme=https"
      - "traefik.http.middlewares.known-ips.ipwhitelist.sourceRange=192.168.0.1/24,127.0.0.1/32"
      - "traefik.http.middlewares.auth-users.basicauth.realm=Admin"
      - "traefik.http.middlewares.auth-users.basicauth.users=test:$$apr1$$bLaRU9Rq$$n/9/kkrM54oF0Lsai7hYn0"
    networks:
      - pub-network
      - pri-network
    ports:
      - 80:80
      - 443:443
      - 8082:8082
    secrets:
      - namesilo_api_key
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
