version: "3.5"

### Networks ###
networks:
  app-network: {}
  pri-network:
    external: true
    name: reverse-proxy

### Services ###
services:
  ### Web service ###
  webapp:
    image: nginx:alpine
    depends_on:
      - phpapp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.entrypoints=http,https"
      - "traefik.http.routers.webapp.rule=Host(`app.${DOMAIN:-emaple.com}`)"
      - "traefik.http.routers.webapp.middlewares=https-only"
      - "traefik.http.routers.webapp.service=webapp"
      # - "traefik.http.services.webapp.loadbalancer.server.port=80"
      - "traefik.http.routers.webapp.tls.certresolver=namesilo"
      - "traefik.http.routers.webapp.tls.domains[0].main=emaple.com}"
      - "traefik.http.routers.webapp.tls.domains[0].sans=*.emaple.com}"
    networks:
      - app-network
      - pri-network
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./vhost.conf:/etc/nginx/conf.d/default.conf:ro

  ### App service ###
  phpapp:
    image: php:7.3-fpm-alpine
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
