version: "3.5"

### Networks ###
networks:
  app-network: {}
  pri-network:
    external: true
    name: reverse-proxy

### Services ###
services:
  ### Web service ###
  webapp:
    image: nginx:alpine
    depends_on:
      - phpapp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webapp.rule=Host(`example.com`)"
      # - "traefik.http.routers.webapp.entrypoints=https"
      - "traefik.http.routers.webapp.entrypoints=https"
      - "traefik.http.routers.webapp.tls.certresolver=mydnschallenge"
      - "traefik.http.routers.webapp.middlewares=https-only"
      # - "traefik.http.middlewares.https-only.redirectscheme.scheme=https"
    networks:
      - app-network
      - pri-network
    restart: unless-stopped
    volumes:
      - .:/var/www/html
      - ./vhost.conf:/etc/nginx/conf.d/default.conf

  ### App service ###
  phpapp:
    image: php:7.3-fpm-alpine
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
